### ISSUE TITLE
Remove CoinPayments From "Spend" Dropdown

### ISSUE THREAD

**Issue by barton2526** [gridcoin-community/Gridcoin-Site#102]
CoinPayments no longer supports Gridcoin on their platform 😦 

https://www.coinpayments.net/supported-coins

**Comment by grctest** [comment]
https://blog.coinpayments.net/announcements/may-2-2018-coin-delistings

Damn, happened back in May.. its removal sound good :+1:

**Comment by grctest** [comment]
Done, will be included in today's merge request.
