### ISSUE TITLE
Add new block explorers

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Site#104]
I believe we're missing one or two block explorers, can anyone confirm this?

**Comment by Pythonix** [comment]
The only other block explorer I can think of is the one from holytransaction.
[HolyTransaction Gridcoin Explorer](https://gridcoin.holytransaction.com/)

**Comment by ryanlatterell** [comment]
Is this essentially a distributed scheme still?

**Comment by ryanlatterell** [comment]
How does it all work?

**Comment by grctest** [comment]
To learn about gridcoin, please visit gridcoin.us - this page is for
helping develop said website.

**Comment by barton2526** [comment]
@grctest What exactly are we still missing?

**Comment by grctest** [comment]
Looks like we've got them all now 👍
