### ISSUE TITLE
Improve Results from Website Loading Test

### ISSUE THREAD

**Issue by RoboticMind** [gridcoin-community/Gridcoin-Site#107]
I ran a test from webpagetest.org and received results that need to be improved

here's the link to the results
https://www.webpagetest.org/result/180703_81_495c5c2696ca6333050a672db914400d/

**Comment by barton2526** [comment]
Results are much better now (I didn't change anything on the site...)

https://www.webpagetest.org/result/180704_EM_5bde84defb9ab7cd96e18ee699c21d64/

**Comment by barton2526** [comment]
I am putting a bandage on this by upgrading our UI KIT to version 1.0.1 which reduces the size of the font files from 2 MB to 100 KB.  This should decrease page load times substantially (fonts were slow to load).

**Comment by barton2526** [comment]
https://www.webpagetest.org/result/180711_AY_c0616d76da5ada177e37bc4289089efe/1/details/#waterfall_view_step1

Further investigation needed for the background image size.

**Comment by barton2526** [comment]
https://www.webpagetest.org/result/180711_AY_c0616d76da5ada177e37bc4289089efe/1/details/#waterfall_view_step1

Further investigation needed for the background image size.

**Comment by barton2526** [comment]
Now running with StatusCake (https://www.statuscake.com/).  Will continue to monitor page load times.

**Comment by grctest** [comment]
Anything else we can do to speed things up? The nginx configuration may need some tweaking @Foggyx420

**Comment by RoboticMind** [comment]
I've rerun the tests (still under 4g) since a lot has changed to see where things are at:
https://www.webpagetest.org/result/190223_ZM_23906d0ab0870491384b0a163048ec12/

**Comment by RoboticMind** [comment]
Rerun again (under 4g again) since we've changed things up, https://www.webpagetest.org/result/190518_YA_1b2c2171be5324d1d47edbd29a06eacc/ now the effective use of CDN is checked. Overall load time seems to be around 2 seconds faster. Starts rendering about 1 second faster. Still some more work to be done especially looking at the [lighthouse report](https://www.webpagetest.org/lighthouse.php?test=190518_YA_1b2c2171be5324d1d47edbd29a06eacc&run=2)

**Comment by RoboticMind** [comment]
Rerun again due to the GitHub pages switch https://www.webpagetest.org/result/190529_F4_345601ce7fa487c1bcbe639fd15ee256/

**Comment by barton2526** [comment]
Can this be closed?

**Comment by RoboticMind** [comment]
I think so. Even on 4g the results look pretty good with only 1.45 seconds from first request with zero cache to a rendered page. https://www.webpagetest.org/result/210408_AiDcMD_3d6f4b6db2002241cef943936d1374be/

The main thing that would be good to do is probably make the cache time longer for more things. It's extremely aggressive right now at 10 minutes for most stuff. I think that would be something @iFoggz could help with
