### ISSUE TITLE
Replace fontawesome?

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Site#11]
Some users block fonts (even locally downloaded, not using CDN's) with ublock; should we remove font icons, switch to a more FOSS font (possibly evading font blocking), swich to images instead of fonts or lastly remove icons entirely from the website?

Footer w/ icons for reference:
![image](https://user-images.githubusercontent.com/15861527/29686185-f8b3df92-890f-11e7-8968-4118acd06428.png)

**Comment by arminrosu** [comment]
Remove the icons please, they are of no benefit.

**Comment by grctest** [comment]
I wouldn't say they were of no benefit - without them if looks more like a wall of text.

**Comment by Peppernrino** [comment]
i was thinking of making a bunch of tiny .png files to use as icons, but then we would have to follow branding guidelines for each social site, etc. i have the old social images, it wouldn't be that hard... but they wouldn't be purple.

and yeah, i agree with OP. i'm always getting hacked through my fonts. @grctest is always scripting viruses into messages he sends me. ;) quite seriously though, remote fonts have been shown to be a weakness to some degree before (reliance on things. if fontawesome gets hacked, so do we), and in the interest of decentralization...

**Comment by grctest** [comment]
We could download the font pack and host locally instead of fetching them remotely, negating the need for decentraleyes

**Comment by Peppernrino** [comment]
i'll have a go at getting this done.

**Comment by grctest** [comment]
Fontawesome has been removed from the site, where appropriate there are unicode emojis in place (tables). The header and footer no longer have the icons.
