### ISSUE TITLE
Index square social icons redundant & out of place?

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Site#12]
![image](https://user-images.githubusercontent.com/15861527/29694232-a8a9fa4a-8932-11e7-8b17-096f76c43a1f.png)

On the index page, we currently show the social media links as large square (for the most part) icons at the bottom.

Two issues/thoughts:
* The community/social media links are displayed immediately below the square icons in the footer (as shown in the image above); their presence is arguably redundant.
* The multiple colours of the icons now somewhat clash with the purple/black.

Ideas:
* Remove the icons? May make the index page overly minimalist though?
* Unified icon colour scheme?

**Comment by Peppernrino** [comment]
whatever happens, i'd like to see more of the sites included. i'll re-add the pull from your test repo into here tomorrow morning, and we'll go from there. :)

**Comment by grctest** [comment]
They've been pulled and placed in the 'old data' folder.

We can certainly continue adding links to the header/footer 👍 

Perhaps, a talkshoe link under media would be smart?

**Comment by grctest** [comment]
Fully removed at this point.
