### ISSUE TITLE
Include links to resources for making one's own VC project

### ISSUE THREAD

**Issue by an0n7mous3** [gridcoin-community/Gridcoin-Site#123]
I think we should include links to the (apparently limited) resources available on making one's own volunteer computing BOINC project. 

Specifically:
http://www.spy-hill.net/myers/help/boinc/Create_Project.html
https://github.com/marius311/boinc-server-docker

**Comment by grctest** [comment]
We link to the docker repo alongside the gridcoin download links on the
front page.

**Comment by grctest** [comment]
The spyhill link also was updated a long time ago:

>  Last modified: 1 January 2012

**Comment by RoboticMind** [comment]
#276 would close this
