### ISSUE TITLE
currently no link to debian downloads

### ISSUE THREAD

**Issue by gustav1976** [gridcoin-community/Gridcoin-Site#135]

**Comment by barton2526** [comment]
This is pending @caraka

**Comment by RoboticMind** [comment]
Isn't this fixed now/fixable with the Debian files being on GitHub releases now?

**Comment by ShmoogleOsukami** [comment]
I think the site has had links to deb packages for quite a while now and yes with .deb packages being on the github releases this is fixed. So I'll go ahead and close this.
