### ISSUE TITLE
Change slack links to new invite portal

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Site#14]
@NeuralMiner created an invite portal on heroku as a replacement to the http://teamgridcoin.signup.team/ signup page which relied on todoslack bot which is shutdown.

https://grcinvite.herokuapp.com/

Edit: Don't use the heroku app link, neuralminer said he's looking into a custom domain name.

**Comment by xPh03n1x** [comment]
Slack now supports invite links without expiration. Unless the TeamGridcoin Slack is limited for some reason, I don't see why a separate dedicated app would be necessary for this.
