### ISSUE TITLE
Table responsive design ineffective

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Site#142]
Google's complaining that "Clickable elements are too close together" on the RPC command reference page - checking this using a mobile phone confirms that only the first column is shown on small screens.

How should we proceed? Should we just link to the RPC reference page on the gridcoin-research github wiki instead of maintaining this page?

Should we try adding a horizontal scroll bar?

Should we hide columns on smaller screens?

**Comment by grctest** [comment]
This also affects the solo/pool/investor comparison table on the index page, the investor column is half cut off.

**Comment by ShmoogleOsukami** [comment]
Updating to bootstrap 4.3.1 so far as resulted in the tables being a lot more responsive and fit perfectly for mobile sized viewports. So we should be able the close this issue when I get bootstrap updated and fix all the css that breaks.

**Comment by barton2526** [comment]
Pending #156

**Comment by ShmoogleOsukami** [comment]
Fixed as of #176
