### ISSUE TITLE
Exchange

### ISSUE THREAD

**Issue by michalkania** [gridcoin-community/Gridcoin-Site#144]
You may want to try add GRC to bitbay exchange what is considered to be No.1 in Poland. It supports direct payments/withdrawals with FIAT currency (EUR, USD, PLN), so I guess it's worth to at least try.

https://bitbay.net/en/news/add-your-coin-or-token-on-bitbay

**Comment by grctest** [comment]
Voting mechanisms for implementation are a nightmare, but if they integrate Gridcoin we can certainly add their links to the gridcoin website.

**Comment by barton2526** [comment]
Exchange listing has little to do with the website repo.  Closing
