### ISSUE TITLE
Add QQ Group Number To Site

### ISSUE THREAD

**Issue by RoboticMind** [gridcoin-community/Gridcoin-Site#147]
From mrip01 on slack 

> can you guys add the QQ (Tencent Social software) number 258951963 to the gridcoin.us website?
> Chinese people use this QQ group to communicate the Girdcoin topic
> it is named 格雷德GRC（中国总群）

mrip01 also said that it can be put like this for a link: 

> 点击链接加入群聊【格雷德GRC(中国总群)】：https://jq.qq.com/?_wv=1027&k=5fDyjCV

in hypertext it would look like: 
[点击链接加入群聊【格雷德GRC(中国总群)】](https://jq.qq.com/?_wv=1027&k=5fDyjCV)

Probably should be added to the Community section in the header and footer

**Comment by grctest** [comment]
Does this code not change? Or am I thinking of wechat invite qr codes?

**Comment by ShmoogleOsukami** [comment]
Still unsure about adding this based on how google translated the text. 
格雷德GRC Transtales to Greed GRC apparently, I'd sooner have it say Gridcoin QQ chatroom in Chinese or something

**Comment by mrip0001** [comment]
> 
> 
> Still unsure about adding this based on how google translated the text.
> 格雷德GRC Transtales to Greed GRC apparently, I'd sooner have it say Gridcoin QQ chatroom in Chinese or something

How can I help?

**Comment by mrip0001** [comment]
> 
> 
> Does this code not change? Or am I thinking of wechat invite qr codes?

I think it does not change. I've tested with links of some groups from a year ago.

**Comment by mrip0001** [comment]
> 
> 
> Still unsure about adding this based on how google translated the text.
> 格雷德GRC Transtales to Greed GRC apparently, I'd sooner have it say Gridcoin QQ chatroom in Chinese or something

I think that's right. You can also use "Gridcoin China QQ group".

**Comment by ShmoogleOsukami** [comment]
> Still unsure about adding this based on how google translated the text.
> 格雷德GRC Transtales to Greed GRC apparently, I'd sooner have it say Gridcoin QQ chatroom in Chinese or something
> 
> I think that's right. You can also use "Gridcoin China QQ group".

If you could get me the translation for "Gridcoin China QQ group" I can get it  a PR done for it, I don't trust google translate to provide 100% accurate translations xD

**Comment by barton2526** [comment]
Closed with #155
