### ISSUE TITLE
Remove Bisq Exchange from site.

### ISSUE THREAD

**Issue by ShmoogleOsukami** [gridcoin-community/Gridcoin-Site#148]
We've been removed from the Bisq network 5 days ago in the following pull request.
https://github.com/bisq-network/bisq/pull/2434

**Comment by grctest** [comment]
That sucks, they're listed in the guides as well as the header/footer, makes sense to remove them.

**Comment by ShmoogleOsukami** [comment]
Issue can be closed with https://github.com/gridcoin-community/Gridcoin-Site/pull/151 being merged.
