### ISSUE TITLE
Now-UI-Kit Update or remove?

### ISSUE THREAD

**Issue by ShmoogleOsukami** [gridcoin-community/Gridcoin-Site#153]
There is a new version of Now-UI-Kit available, version 1.2.0 We can either update to it or completely remove now-ui-kit. 

I'm not sure how much of now-ui-kit we use at the moment, There is a previous issue https://github.com/gridcoin-community/Gridcoin-Site/issues/44 that suggests it's no longer required.

Thoughts?

**Comment by ShmoogleOsukami** [comment]
Removal is doable, The only thing that I can't replicate in bootstrap would be how the nav bar gets colour on scroll, I can probably do something similar in css or sue a combination of bootstrap css and js to do it. Will be looking into that tomorrow.

**Comment by grctest** [comment]
I wouldn't worry about this, we can easily update in the future.
Replicating the kit is unnecessary.
