### ISSUE TITLE
Need to put reasonable balance required for solo staking in solo guide

### ISSUE THREAD

**Issue by jamescowens** [gridcoin-community/Gridcoin-Site#154]
This screen...
![image](https://user-images.githubusercontent.com/7529186/54092653-0b308d80-4365-11e9-9748-daa5642f669f.png)

Should have something like...

In order to earn more Gridcoin, you need to crunch one or more whitelisted BOINC projects within team Gridcoin. You must install the BOINC client, select several BOINC projects and get crunching!

To retrieve your crunching rewards by solo mining, you must have a balance of Gridcoin sufficient to stake before 180 days elapses. To be safe you should have have enough Gridcoin to stake approximately once every month. Averaging statistics over the last month, this would be x GRC. GRC can be acquired in a number of different ways. [link] You can also start out by pool mining, which requires no initial investment of Gridcoin to retrieve your rewards.

BOINC video introductions:
David Anderson talks BOINC, Citizen Science, and Why We Still Need You!
Serge Berig - BOINC: Compute for Good, Change the World

**Comment by ShmoogleOsukami** [comment]
Issue complete with PR #157
