### ISSUE TITLE
SEO/other optimizations

### ISSUE THREAD

**Issue by RoboticMind** [gridcoin-community/Gridcoin-Site#159]
I've run a bunch of SEO optimization reporting sites and here are the sites and reports:
https://seositecheckup.com/seo-audit/gridcoin.us
https://www.seoptimer.com/gridcoin.us
https://www.woorank.com/en/www/gridcoin.us
https://iwebchk.com/reports/view/gridcoin.us

These are some of the common things coming up to do:
- [x] Adding a sitemap for web crawlers 
- [x] Adding `<h1>` tags
- [x] Stop returning server signature 
- [x] shorten description in meta tags
- [x] minimfy css and js

There's a lot more in these reports that get really specific, so reading each of them is worthwhile

**Comment by barton2526** [comment]
CSS and JS appears to be minified now.

**Comment by ShmoogleOsukami** [comment]
#193 will sort out the sitemap.

**Comment by barton2526** [comment]
`Congratulations! Your website has a sitemap file. `

**Comment by ShmoogleOsukami** [comment]
Quick question, have we stopped returning server signature since moving to github pages?

**Comment by RoboticMind** [comment]
`Congratulations, your server signature is off.` looks like it, however we should check if it also doesn't on wiki.gridcoin.us and downloads.gridcoin.us

**Comment by RoboticMind** [comment]
Looks like the description in the meta tag was shortened at some point, so we can check that off the list

**Comment by RoboticMind** [comment]
Server signatures appear to all just say Cloudflare so I think that can be checked off

**Comment by RoboticMind** [comment]
H1 tag changes in #176 should let us check of the no h1 tags

**Comment by RoboticMind** [comment]
`Your page is making good use of header tags.` Think we can check that off and close this
