### ISSUE TITLE
Community Discord invite link

### ISSUE THREAD

**Issue by 47an** [gridcoin-community/Gridcoin-Site#167]
Homepage share Discord.me link to generate a temp invite using widget set on server. This is no longer possible as Discord.Me have wiped server listed and accept new created at beta instead.
I deauthorize server manage connection on my account and discord.me and i am no longer able to administrate old site.

This https://discord.me/gridcoin should not be use anymore.

Possible for Discord owner to create a new url but suggest not to use it as they force bot and connect server to one user. My experience https://discord.me/gridcoin page I would suggest to not use Discord.Me and would not support anyone using it for Gridcoin. 

I suggest to share invite link without any time limit as it was before:
Old invite link generated by me: https://discord.gg/Bt4YHxJ
New generated by me: [no limit] https://discord.gg/re979wZ
Generated by Neuralminer: https://discordapp.com/invite/jf9XX4a

Or set to another new link.

**Comment by RoboticMind** [comment]
@ShmoogleOsukami This seems kind of close to what you were saying about getting a vanity discord URL
