### ISSUE TITLE
I get 400 Bad Request Request Header Or Cookie Too Large error at gridcoin.us

### ISSUE THREAD

**Issue by kotenok2000** [gridcoin-community/Gridcoin-Site#169]
Here is my request. https://pastebin.com/3vgiPe1e

**Comment by tomasbrod** [comment]
Only unusual thing is the accept-language header.
https://gridcoin.us/ loaded for me just right. What are you trying to do, just access the page in browser?
Can someone else confirm?

**Comment by kotenok2000** [comment]
I think it was because i added all the languages in chrome settings https://imgur.com/a/rswEsSM

**Comment by cyrossignol** [comment]
@kotenok2000 Looks like this is working now. Can you please check again?
