### ISSUE TITLE
100% height usage

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Site#17]
Currently, some pages with not much information (exchange, blog, contact) have their footer higher than the bottom of the screen when on larger resolutions, so there's the dark background below the purple footer.

**Comment by ShmoogleOsukami** [comment]
I just this very second figured out how to fix this. I should be able to get a PR up today or tomorrow.

**Comment by ShmoogleOsukami** [comment]
Problem fixed as of PR #160
