### ISSUE TITLE
Add Compliance for UK/EU Cookie laws

### ISSUE THREAD

**Issue by ShmoogleOsukami** [gridcoin-community/Gridcoin-Site#172]
Simply put we need to inform users of the use of cookies and so on.

Currently we have only one which is cloudflare related. Which they say is used to help them track malicious users with relation to blocking bad users and does not allow cross-site tracking.

**Comment by kjreills** [comment]
I am going to start working on this. Is it alright if I use an open source library such as [this one](https://github.com/dobarkod/cookie-banner)? Any preferences on style?

**Comment by barton2526** [comment]
If you decide to use that library, I think it would be preferable if we installed it locally rather than pulling if over a CDN

**Comment by RoboticMind** [comment]
I should note that the Cloudflare cookies are not really an issue with GDPR; the Google Analytics one ia what is more an issue. The Clouflare cookies are essential cookies. We couldn't disable most of them if we wanted to if I understand correctly.

**Comment by kjreills** [comment]
Thanks for the suggestions! I ended up going with a different library that I liked better, but I did pull the source code directly into this repo. The PR is up if anyone has some time to look at it, and I welcome any and all feedback. Thanks!
