### ISSUE TITLE
Add list of addnodes to website

### ISSUE THREAD

**Issue by ShmoogleOsukami** [gridcoin-community/Gridcoin-Site#173]
The website lacks a list of addnodes.
I'm thinking of having a page that will link to places like gridcoin.pl and also list known, stable addnodes.

**Comment by RoboticMind** [comment]
maybe we could link to @cyrossignol 's site https://addnodes.cycy.me/ ?

**Comment by startailcoon** [comment]
The new Gridcoinstats page will monitor nodes on the network over time, both to make a visual map of where nodes are located (by IP) and to possible make a list of nodes that can be added that has a long uptime.

**Comment by sweede-se** [comment]
List is available in wiki. Close issue?
