### ISSUE TITLE
Youtube links within the Solo and Pool Guides

### ISSUE THREAD

**Issue by jimbo-slice** [gridcoin-community/Gridcoin-Site#18]
http://gridcoin.us/Guides/boinc-install.htm
http://gridcoin.us/Guides/pool.htm

These two pages share some of the same info, including the section near the top titled "BOINC video introductions". The first link, currently titled "David Anderson talks BOINC, Citizen Science, and Why We Still Need You!" actually takes you to the video for how to join grcpool. 

The second link, titled "Serge Berig - BOINC: Compute for Good, Change the World" does include a clip of David Anderson talking about BOINC.

**Comment by grctest** [comment]
Cool, fixed in the dev version & will push fix live in the near future. Thanks 👍
