### ISSUE TITLE
Remove Delisted Projects from Whitelist

### ISSUE THREAD

**Issue by barton2526** [gridcoin-community/Gridcoin-Site#187]
As of May 29, DrugDiscovery and Citizen Science Grid are to be removed from the whitelist as a result of two recent polls passing.

As of May 31, Enigma will be removed from the whitelist as they have removed new user signups.

Not sure if it's best to do this as two separate PRs or one we just submit on the 31st.  Discuss.

**Comment by ShmoogleOsukami** [comment]
Depends on if we are keen to deploy the site asap or not. If CM is to busy to deploy a pr to remove DrugDiscovery and CSG before the 31st we might as well wait and do it in one pr on the 31st.

It won't take much work at all to get a PR build and ready to merge. Could do it now and be done in a couple of minutes.

As far as I know we'll just be updated the whitelist.yml in _data right.

**Comment by barton2526** [comment]
Closed with #188 and #199
