### ISSUE TITLE
Proposed simplified guide comparison

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Site#20]
![image](https://user-images.githubusercontent.com/15861527/29902506-883d7980-8df6-11e7-8c98-f3925f3c6a03.png)

# VS

![image](https://user-images.githubusercontent.com/15861527/29902483-629bbd36-8df6-11e7-9af8-a2bae66d3a52.png)

Thoughts? 

Text vs Ticks/Crosses? Colours for the ticks/crosses? Perhaps rather than having red x's, use a single dash? " - "

A positive outcome from the table view is that it prevents using terminology like 'disadvantages' which could come off as negative, despite being presented for comparison.

**Comment by grctest** [comment]
https://github.com/gridcoin-community/Gridcoin-Site/commit/01da745138aa49d5efb5265701aa11820ebde6af

**Comment by jimbo-slice** [comment]
I prefer the look of the ticks/crosses, but it would be better if we could stick with green checks and red ticks, and avoid red checks and green ticks, imo :-)

We'd just have to re-phrase the first statement to achieve this. I'll think about it for a second and type another reply.

I don't think we need to label our guide row with the word "Guides"

**Comment by jimbo-slice** [comment]
The table is much better than the wall of text by the way.

**Comment by jimbo-slice** [comment]
We could add a row called "Helps secure the network", with checks for solo and investor, and a tick for pool.

**Comment by grctest** [comment]
![image](https://user-images.githubusercontent.com/15861527/29902942-0d20c3e4-8df9-11e7-9d2b-335e72dfca65.png)

Change from crosses to minus, also first row promotes requiring GRC as good (green) haha!

> We could add a row called "Helps secure the network", with checks for solo and investor, and a tick for pool.

Good idea 👍

**Comment by jimbo-slice** [comment]
I like the white minuses better than the multi-colored checks and crosses. The user should be able to understand which are advantages and which aren't. For instance, no fees for solo crunching, they should be able to realize that's a good thing.

Few more thoughts:

Earn Interest via POS: "Earn 1.5% APR" might be better, as I don't think the rate will be mentioned elsewhere on the landing page.

Statistics sites: I prefer something like "Global BOINC Leaderboards" with check mark/minus/minus for the three categories.

**Comment by jimbo-slice** [comment]
> Change from crosses to minus, also first row promotes requiring GRC as good (green) & the same for pool fees, lol!

Maybe change 'fees on rewards' to 'no fees'

**Comment by jimbo-slice** [comment]
Sorry if I'm cluttering up the comments here, but I'm just posting ideas as they come :-)

We don't need to lead off with "requires initial balance", we should order this list from most to least important. Something like this:

1) Earn BOINC Rewards
2) Earn 1.5% APR
3) Helps Secure Network
4) Decentralized
5) Ability to Vote
6) Fees
7) Requires Initial Balance
8) BOINC Leaderboards

<and remove the word "guides", the buttons at the bottom are sufficient>

**Comment by grctest** [comment]
> Statistics sites: I prefer something like "BOINC Leaderboards" with check mark/minus/minus for the three categories.

There's not just BOINC but also Gridcoin statistics, though I think most are only interested in the BOINC stats side of things..

---

I'll try out some of your additionally proposed changes to the table, give me 10 mins.

**Comment by grctest** [comment]
Alright, changes have been made & the old guide comparison moved to the 'old data' folder.

![image](https://user-images.githubusercontent.com/15861527/29924805-1e12485a-8e56-11e7-821e-178032fd226e.png)

Good to go live with the changes?

**Comment by grctest** [comment]
Should we replace the minus characters with N/A ?

A minus on 'fees on rewards' conveys this as a negative, when it is in fact a positive.

Another user suggested switching the checks to white and the minuses as purple, so as to increase focus too.

**Comment by jimbo-slice** [comment]
"Fees on Rewards" and "Requires an initial balance" don't fit the format (an answer of "yes" is a disadvantage). We should change them to "Keep 100% of Rewards" and "No Upfront Investment". Then, reverse the current symbols for those two rows.

That way, every time there is a checkmark, it's referring to a positive attribute.

**Comment by jring-o** [comment]
Are we planning on changing the background color away from dark?  

If we have a white/gray/light colored background I think black text and table borders, red and green checks and x's, and purple buttons might look nice.

Might not.

**Comment by grctest** [comment]
We could switch colour palettes possibly, though we'd need to mess around with the now-ui kit because it's specialized for darker themes.

**Comment by grctest** [comment]
> "Fees on Rewards" and "Requires an initial balance" don't fit the format (an answer of "yes" is a disadvantage). We should change them to "Keep 100% of Rewards" and "No Upfront Investment". Then, reverse the current symbols for those two rows.

Done

**Comment by jring-o** [comment]
> We could switch colour palettes possibly, though we'd need to mess around with the now-ui kit because it's specialized for darker themes.

I don't know what what means = ) but i'd be happy to help do what I can if someone wants to show me

User Bayard on slack mocked up what a light scheme might look like (sorry for the quality, just copy pasting from slack):

![image](https://user-images.githubusercontent.com/29245250/29996003-652c7390-8fc4-11e7-87cd-d2d18ae9ef80.png)

![image](https://user-images.githubusercontent.com/29245250/29996010-8994a02c-8fc4-11e7-95eb-a7e8edc297f5.png)

![image](https://user-images.githubusercontent.com/29245250/29996011-8e6c3330-8fc4-11e7-852c-0ac824f68572.png)
