### ISSUE TITLE
Remove gridcoin basic info link from Navbar

### ISSUE THREAD

**Issue by ShmoogleOsukami** [gridcoin-community/Gridcoin-Site#203]
Referring to https://www.reddit.com/r/CryptoWikis/wiki/gridcoin_basicinfo
The information we link to here is out of date. We should remove the link with the goal of re-adding when the information has overhauled.

@jring-o has plans to overhaul the information in the future.

**Comment by RoboticMind** [comment]
Was this done in #208 ?

**Comment by ShmoogleOsukami** [comment]
Fixed in #212
