### ISSUE TITLE
"What is Gridcoin?"  -  Typo

### ISSUE THREAD

**Issue by jimbo-slice** [gridcoin-community/Gridcoin-Site#21]
![whatisgridcoin](https://user-images.githubusercontent.com/26789781/29929792-5442808c-8e21-11e7-83a9-493a41560666.png)

Paragraph 4 final sentence:

Current: "Volunteer computing is substantially cheaper than cloud computing services, the" 
Revised: "Volunteer computing is substantially cheaper than cloud computing services."

**Comment by grctest** [comment]
I'll fix this soon, thanks 👍 

I'd appreciate similar proof reading of the rest of the website if you were so brave? ⚔️

**Comment by jimbo-slice** [comment]
Sure, I'll keep posting errors as I see them and leave the actual modification to someone else (haven't learned how to do that yet).
