### ISSUE TITLE
Possibly needed change to QQ link

### ISSUE THREAD

**Issue by RoboticMind** [gridcoin-community/Gridcoin-Site#211]
Mrip01 from slack said that the link to QQ needed to be changed
> gridcoin qq 集团 is wrong. it should be qq 群

Not sure if that's correct/needed since I belive Mrip01 gave the transaltion from before in #147. I'm not sure though because I don't know Chinese very well.

**Comment by ShmoogleOsukami** [comment]
The original translation was from mrip01. I asked for clarification on slack at the time as the google translation came out to be something a little strange. Like the link had the term Greed GRC in it which makes it sound like a pump and dump group imo. So he suggesting the current term as an alternative.

Granted. I have just done a google translate. Both terms translate to the same word however qq 群 is probably more grammatically correct. So I think we should change it.
