### ISSUE TITLE
RPCReference.htm needs reformatting and updating.

### ISSUE THREAD

**Issue by ShmoogleOsukami** [gridcoin-community/Gridcoin-Site#215]
The RPC Reference needs formatting with a table much like how the terminology page is done.
While we're at it we can update the list of commands.

We should follow the same catagory grouping the wallet does when you type help in debug console.
Current category in the wallet are:
- wallet
- mining
- developer
- network

**Comment by barton2526** [comment]
This page no longer exists.  Closing
