### ISSUE TITLE
Clicking on the logo opens new tab

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Site#23]
If you click on the gridcoin logo in the header you are linked to the landing page as expected. It is opened in a new tab though. I tried in firefox and chrome. I don't know if that is intended but it feels a little bit strange to me.

**Comment by grctest** [comment]
Hmm.. this is the case for me too 👎 

I'll look into this 👍

**Comment by grctest** [comment]
I had target="_blank" added to the hyperlink for some reason, with its removal it no longer opens a new tab. This will be added in along side several other changes later on.

Thanks for reporting this issue.
