### ISSUE TITLE
List publications and press releases about Gridcoin

### ISSUE THREAD

**Issue by Pythonix** [gridcoin-community/Gridcoin-Site#240]
It might be a good idea to refer to serious articles / papers that discuss Gridcoin on the website.

For example:

* [Environmentalism in Cryptoanarchism: Gridcoin Case Study](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3131232)
* [A Review of Distributed Supercomputing Platforms Using Blockchain](https://link.springer.com/chapter/10.1007/978-981-15-4218-3_13)
* [Sidecoin: a snapshot mechanism for bootstrapping a blockchain](https://arxiv.org/abs/1501.01039)
* [Distributed pool mining and digital inequalities, From cryptocurrency to scientific research](https://www.emerald.com/insight/content/doi/10.1108/JICES-02-2020-0018/full/html)
* [Effizientes Mining: Kryptowährungen für einen besseren Zweck](https://www.computerbase.de/2018-03/effizientes-mining-gridcoin-steem-solarcoin/)

**Comment by RoboticMind** [comment]
Might not be a bad idea to include something like this for the wiki. Might also be a good idea to include press in news along with papers. Could separate the page into two categories one for press and one for papers.

Found some other articles:
[Distributed Consensus Technologies in Cryptocurrency Applications](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.674.1781&rep=rep1&type=pdf)
[Breaking and Fixing Gridcoin](https://www.usenix.org/system/files/conference/woot17/woot17-paper-grothe.pdf)
[Distributed pool mining and digital inequalities, From cryptocurrency to scientific research](https://www.emerald.com/insight/content/doi/10.1108/JICES-02-2020-0018/full/html)
[One of a kind: The tail of citizen science volunteers](https://asistdl.onlinelibrary.wiley.com/doi/epdf/10.1002/pra2.45) (not sure how much this one talks about Gridcoin; there's a pay wall, but it does mention Gridcoin in the abstract)

Ran into a few others that google scholar said Gridcoin was mentioned in but I couldn't check how much it mentioned it. Ran into a fair number that mentioned Gridcoin, but it wasn't a main topic of the paper
