### ISSUE TITLE
Index page copy

### ISSUE THREAD

**Issue by jring-o** [gridcoin-community/Gridcoin-Site#25]
I have reworked the index page introduction to gridcoin section and would appreciate some feedback.

I tried to direct the content more toward the idea behind GRC.

Thanks = )

>Gridcoin seeks to create a decentralized and sustainable distributed processing network which prioritizes both the utilization of existing Idle Processing Potential (IPP) and the creation of a free to host ecosystem for researchers and individuals with data to process.
>
>To this end, Gridcoin has created an open source blockchain based digital asset (Ticker: GRC) secured by Proof of Stake, and which rewards those who volunteer their IPP to the grid computing network, BOINC.  BOINC, The Berkeley Open Infrastructure for Network Computing, is an open-source distributed processing network which provides scientists and enthusiasts with a means to host data for free.  Volunteers then offer their IPP to specific BOINC projects which help map the Milky Way, detect near earth asteroids, find prime numbers, fold proteins, test cures and vaccines, test chemical and molecular combinations, Search for Extraterrestrial Life (SETI), crack codes from WWII, and more. 
> 
>Unlike our competitors, Gridcoin believes that the power to analyze the endless data of the universe belongs to everyone, not just those with the funds to purchase mass volumes of processing power.  Gridcoin also believes that a network which encourages individuals and entities to volunteer their IPP presents a more efficient and sustainable option than a network which incentivizes the centralization of processing power.
>
>By directly rewarding those who volunteer their idle processing power to BOINC, Gridcoin hopes to create an ecosystem in which valuable data, or worthwhile research, is defined by how volunteers move their IPP among the array of projects with no concern for reward.  At the same time, anyone with compatible data can host a project on BOINC and get it completed without the need to purchase processing power.

**Comment by jimbo-slice** [comment]
beautiful!
