### ISSUE TITLE
not found if tap setup gridcoin research client

### ISSUE THREAD

**Issue by givianw** [gridcoin-community/Gridcoin-Site#285]
if i tap "setup gridcoin research client" on [webpage](https://gridcoin.us/guides/noncruncher-gridcoin-setup.htm). it shows "not found"

**Comment by RoboticMind** [comment]
Oh oops it looks like I made a typo there. It appear to only be the "Setup Gridcoin Research Client" at the bottom of the first page and not the link at the top. Fixed in #286

**Comment by RoboticMind** [comment]
@barton2526 can you close this now that it was fixed?
