### ISSUE TITLE
Replace Mac OS link

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Site#30]
Change Mac OS wiki link to: http://wiki.gridcoin.us/OS_X_Guide#DMG_Download_Guide

**Comment by acey1** [comment]
Just to clarify please,

The "MacOS DMG Packages" button on main page should continue to link directly to the git download page here:  https://github.com/Git-Jiro/homebrew-jiro/releases/

The only wiki button that I see is at bottom of main page "W Gridcoin Wiki" and should continue to link to the main wiki "File Talk" page (which is a redirect from the main page for some reason unknown) here: http://wiki.gridcoin.us/Main_Page

I do not yet see a "Mac OS wiki link" as stated in the change request above. I suggest we make a separate button labeled, "MacOS Installation Guide" to help the many unfamiliar people using macOS get the App installed and running properly. Link here same as above:  http://wiki.gridcoin.us/OS_X_Guide#DMG_Download_Guide
