### ISSUE TITLE
Add coinomi recover guide to guides or wiki

### ISSUE THREAD

**Issue by nathanielcwm** [gridcoin-community/Gridcoin-Site#309]

**Comment by delta1513** [comment]
I'm willing to make this guide based on this one [here](https://www.reddit.com/r/gridcoin/comments/k3jcfi/comment/ge3vdt7/?utm_source=share&utm_medium=web2x&context=3)

Just wondering if this is still worth doing considering it's been so long.

**Comment by nathanielcwm** [comment]
I agree that we might as well just link to that guide instead of integrating it into the wiki due to age.
