### ISSUE TITLE
Replace header background

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Site#31]
The purple gradient header background is just a filler, what should we replace the background with?

### Royalty-free/Creative-Commons media:

* https://eros.usgs.gov/imagegallery
* https://www.nasa.gov/multimedia/guidelines/index.html
* https://asterweb.jpl.nasa.gov/gallery-detail.asp?name=lena

**Comment by jring-o** [comment]
a fade in/out series of high rez images = )

**Comment by acey1** [comment]
The purple right now is over-powering and hurts the eyes a bit. Can it be softened up?

**Comment by grctest** [comment]
Changed the purple background & the logo.

**Comment by acey1** [comment]
Awesome! The page navigation is a lot more intuitive with e new logo favicon to boot. Nice job!
