### ISSUE TITLE
Mention GDPR earlier in page

### ISSUE THREAD

**Issue by makeasnek** [gridcoin-community/Gridcoin-Site#327]
Noticing on this page:
https://gridcoin.us/guides/earn-grc.htm

On step H, it may be useful to say "Check if your project needs GRPR consent for exporting your stats". This is mentioned later in the page under the heading Q: My Beacon Isn't Being Verified. Since it's a common reason a beacon wouldn't pass verification, seems wise to head that off when the user is doing their username update.

**Comment by RoboticMind** [comment]
I have this included in a big overall of the guides I'm working on. Since I've been busy, it's taken me a while. I might just be able to cherry-pick it out so that's updated sooner
