### ISSUE TITLE
We need a Favicon please

### ISSUE THREAD

**Issue by acey1** [gridcoin-community/Gridcoin-Site#33]
It would be a nice touch if we added a Favicon to the Gridcoin site, so our logo shows up in saved book marks on internet browsers.

**Comment by Peppernrino** [comment]
i was thinking this exact thing a few days ago!

**Comment by grctest** [comment]
https://github.com/gridcoin-community/Gridcoin-Site/blob/master/source/layouts/partials/_head.erb#L25

We need to pre-pend "/Images/Favicons/" to each of the favicon links.

**Comment by acey1** [comment]
Nice work! Can't wait to see it.

**Comment by acey1** [comment]
Hey the new website looks great!  We now have a favicon, but it is the old style logo. Is this intended?

**Comment by grctest** [comment]
Fixed
