### ISSUE TITLE
Official guide still mentions joining the Gridcoin BOINC team is a requirement

### ISSUE THREAD

**Issue by delta1513** [gridcoin-community/Gridcoin-Site#335]
Since the latest mandatory upgrade, the team requirement has been dropped. Any reference to the Gridcoin team should either be removed or replaced in favour of a clear "Optional" step.

An example is on [this page](https://gridcoin.us/guides/boinc-install.htm) under "No Account Manager Setup"

**Comment by RoboticMind** [comment]
Oh whoops thought I got all of those mentions. In the process of completely rewriting the guides, but I'll put up a quick PR to remove those mentions in the current guides

**Comment by delta1513** [comment]
Please note that my search was not a thorough search so I recommend doing a much more rigorous search for any mentions of it.
