### ISSUE TITLE
Main website download link for Mac is incorrect.

### ISSUE THREAD

**Issue by l008com** [gridcoin-community/Gridcoin-Site#338]
On the gridcoin.us main web page, in the downloads section, the download link for macOS links to Jiro's github instead of the "official" github. That should probably be switched.

HOWEVER Jiro does do builds for older macOS versions so it may make sense to link to both. 
The page could indicated the supported OS versions for each of the two download links. 

Also just a minor nitpick, the M in "MacOS" should be lowercase, so "macOS" <- like that. 
Citation: https://www.apple.com/macos/monterey/

**Comment by RoboticMind** [comment]
I think it should be kept as a secondary link, but now that macOS builds are being made on the main repo, I will point the first link there. Need #332 to be merged before I can mess with the script that gets the download link because otherwise, there will be a git conflict
