### ISSUE TITLE
Add media links to main site

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Site#35]
Links to logo packs, repos, etc.

**Comment by barton2526** [comment]
Can you please elaborate one what specifically you would like to see linked?  Do you mean links to the marketing hub for files?

**Comment by grctest** [comment]
Yeah, pretty much just links to the logo packs and marketing files. I think there's a gridcoin-site repo for most of these files we could link directly to.

**Comment by barton2526** [comment]
Yeah, I can add a link to https://github.com/gridcoin-community/Gridcoin-Marketing

**Comment by barton2526** [comment]
Added in #60

**Comment by barton2526** [comment]
Added in #60
