### ISSUE TITLE
Website update for folding at home.

### ISSUE THREAD

**Issue by Weber462** [gridcoin-community/Gridcoin-Site#361]
Need to add information about Folding at home on 

~https://gridcoin.world~

~GRC is the native currency of the Gridcoin ledger. It is distributed directly to network participants contributing computation cycles to the advancement of science and humanity via the distributed computing infrastructure, BOINC (_add) and Folding@home._~

https://gridcoin.us/

_What is Folding@Home?
Folding@home is a  project aimed to help scientists develop new therapeutics for a variety of diseases by the means of simulating protein dynamics. This includes the process of protein folding and the movements of proteins, and is reliant on simulations run on volunteers' personal computers._

Individuals: Join BOINC (add) _or Folding@home_ and start earning Gridcoin for your contributions! See the table below for more information

~https://gridcoin.world/whitelist.htm
Add Folding@Home to Whitlisted projects.~

~https://gridcoin.world/guides/
Add Folding@home getting started guide.~

**Comment by RoboticMind** [comment]
This should go on https://github.com/gridcoin-community/Gridcoin-World-Site

**Comment by Weber462** [comment]
Looks good to me.  Thank you for doing this. 🙂

**Comment by makeasnek** [comment]
Close the issue then, I think you or the repo maintainer are the only ones who can do it :)

**Comment by Weber462** [comment]
lol.  ill give er a shot.
