### ISSUE TITLE
Additional BTS web wallets

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Site#37]
https://wallet.crypto-bridge.org/market/OPEN.GRC_BTS
Soon: apasia.tech (site currently down)

**Comment by barton2526** [comment]
Not sure how to implement this.  Need additional info.

**Comment by grctest** [comment]
Just a link to the new web wallets as they come online is probably good enough.

RUDEX mentioned on the bitshares podcast recently that they were considering adding gridcoin to their gateway too.

**Comment by barton2526** [comment]
RUDEX is already in.  What further web wallets are needed?

**Comment by barton2526** [comment]
Move to close issue unless another is identified.  @grctest

**Comment by grctest** [comment]
I mean, technically there are like 7 web wallets and many mobile wallets which support the open.grc token, but openledger hasn't re-enabled open.grc yet which sucks 👎

**Comment by grctest** [comment]
Given that Rudex has added Rudex.GRC, it can be used on like 6+ BTS DEX web wallets, think we should only link to RUDEX or should the others get a link too? There's a few mobile wallets too.

**Comment by RoboticMind** [comment]
Aren't these on the site now? Can we close this?

**Comment by barton2526** [comment]
Moving to close this issue
