### ISSUE TITLE
Revamp Project Publications Page

### ISSUE THREAD

**Issue by barton2526** [gridcoin-community/Gridcoin-Site#39]
This page (https://gridcoin.us/Community/ProjectPublications.htm) currently is very out of date and features publications from projects that no longer exist (POEM, malariacontrol.net, etc) and also projects that are no longer whitelisted.  Further discussion should focus on where we want to go with this page, or if we want to forwards users towards a general BOINC publications page.

**Comment by grctest** [comment]
Yeah, to be honest it's just cloned from the BOINC wiki, so we could simply link to the BOINC wiki for project/BOINC publications & cut out a lot of maintenance work.

**Comment by barton2526** [comment]
We already have a BOINC publications page.  Perhaps the two should simply be merged?

**Comment by grctest** [comment]
Perhaps, though we don't regularly update it nor vet the authenticity of linked research - it could be simpler to link to BOINC research publication pages?

**Comment by grctest** [comment]
Removed the page in #140, linking instead to the maintained BOINC wiki page, the 'BOINC publications' has been replaced with a 'BOINC Academic Papers' link which searches Google Scholar for 'BOINC' which returns many BOINC academic papers.
