### ISSUE TITLE
Can we remove Gemfile.lock?

### ISSUE THREAD

**Issue by barton2526** [gridcoin-community/Gridcoin-Site#40]
@grctest Is this file necessary?  It's already included in the git ignore and my local copy differs significantly from what is on the repo.

**Comment by grctest** [comment]
We could remove it as long as it doesn't disrupt a new contributor's environment setup?

**Comment by barton2526** [comment]
Attempting removal: https://github.com/gridcoin-community/Gridcoin-Site/pull/43
