### ISSUE TITLE
Improve quality of exchange logos

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Site#42]
Some of the exchange logos are of low quality, especially the RUDEX logo which is quite pixelated/low-quality. Improving these will give a better impression for users buying GRC.

**Comment by barton2526** [comment]
Added new image for RUDEX exchange.  See https://github.com/gridcoin-community/Gridcoin-Site/pull/43

**Comment by Peppernrino** [comment]
this can be closed with https://github.com/gridcoin-community/Gridcoin-Site/pull/46?
