### ISSUE TITLE
Dead Link in the Footer of Exchange / Exchange seems not listing Gridcoin

### ISSUE THREAD

**Issue by Casraw** [gridcoin-community/Gridcoin-Site#430]
Hi,

Page: https://gridcoin.world/

seems to me that txbit.io is a dead link.

Also on lyp.me i cant find the Gridcoin listed.

Greetings: Casraw

p.s iam confused google finds when i search for grindcoin: https://gridcoin.us/ and perplexity find: https://gridcoin.world/

The dead link is on https://gridcoin.world/ (Is this a valid site?)

**Comment by barton2526** [comment]
This repo is for gridcoin.us. Consider filing this at the gridcoin.world repo

https://github.com/gridcoin-community/Gridcoin-World-Site
