### ISSUE TITLE
Switch bootstrap theme

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Site#44]
Current: https://www.creative-tim.com/product/now-ui-kit

See: https://www.creative-tim.com/bootstrap-themes/ui-kit?direction=desc&sort=number_of_downloads

Material could be a good light replacement: https://www.creative-tim.com/product/material-kit

This will have an impact on the code throughout the website, probably several hours of solid work.

**Comment by barton2526** [comment]
I'd be willing to assist with this.  This theme is really sleek.

**Comment by barton2526** [comment]
Implementation has begun

**Comment by grctest** [comment]
Think this is neccessary anymore? I think the purple theme has been well received..

**Comment by Peppernrino** [comment]
agreed. i think this one could be closed.

**Comment by RoboticMind** [comment]
@barton2526 can we close this now?
