### ISSUE TITLE
Force SSL

### ISSUE THREAD

**Issue by Peppernrino** [gridcoin-community/Gridcoin-Site#48]
Unless you specifically type https://gridcoin.us in the address bar, you end up at plain old gridcoin.us. Was discussed shortly before in a private message, but I neglected to make an issue. My apologies.

**Comment by grctest** [comment]
Server side change @gridcoin

**Comment by Peppernrino** [comment]
Forcing the use of HTTPS:// on your site will ensure that visitors to your site are always using https://gridcoin.us and aren't able to access an insecure http://gridcoin.us URL. This is recommended since if a visitor does access your site as http://gridcoin.us everything will be marked as "Not Secure".

Below code is for forcing HTTPs on an Apache webserver. If you are using another webserver such as lighttpd, nginx, etc you will need to contact your web hosting provider for assistance.

Add the following code to the .htaccess file in your webhosting account:

> RewriteCond %{HTTP_HOST} gridcoin\.us [NC]
> RewriteCond %{SERVER_PORT} 80
> RewriteRule ^(.*)$ https://gridcoin.us/$1 [R,L]

Once this change is made your site will no longer be accessible on the insecure "http://gridcoin.us" URLs and all visitors will be redirected to "https://gridcoin.us" instead.

**Comment by barton2526** [comment]
@gridcoin fixed this today
