### ISSUE TITLE
TLSv1 being phased out on June 30, 2018

### ISSUE THREAD

**Issue by Peppernrino** [gridcoin-community/Gridcoin-Site#49]
We currently have TLSv1 enabled. "This version of TLS is being phased out. This warning won't break our padlock, however if you run an eCommerce site, PCI requirements state that TLSv1 must be disabled by June 30, 2018."

Perhaps we should update just to stay future-proof? There is more talk of an over-the-counter GRC->USD system lately. We may have to be within said guidelines once this happens.

**Comment by barton2526** [comment]
This was referenced in https://github.com/gridcoin/Gridcoin-Research/issues/767

**Comment by barton2526** [comment]
Resolved
