### ISSUE TITLE
Change inline css to proper stylesheets where appropriate

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Site#5]
_From @barton2526 on June 14, 2017 0:49_

Too many pages rely on inline CSS.  This is inefficient and needs to be refactored.

_Copied from original issue: grctest/Gridcoin-Site#33_

**Comment by grctest** [comment]
I have removed a lot of the inline CSS, what's left can likely be smashed into a CSS file.

We could make use of more partials to reduce replicated code.

**Comment by ShmoogleOsukami** [comment]
If you like you can assign this to me or something, I'm about half way through this issue, got index, header and footer done, got 18 more pages to go through but they are pretty small so should be quick.

**Comment by ShmoogleOsukami** [comment]
This issue can be closed now with https://github.com/gridcoin-community/Gridcoin-Site/pull/149 being merged. :)
