### ISSUE TITLE
Investor Guide requires CPID

### ISSUE THREAD

**Issue by ZigzagoonBalloon** [gridcoin-community/Gridcoin-Site#62]
http://gridcoin.us/Guides/investor-acquire-grc.htm 
On step 2: "You need to register your CPID within the Gridcoin network, this is achieved by advertising a beacon transaction to the network. The beacon costs a small amount of GRC and it takes approx 24hrs to register your CPID in the GRC reward mechanism after advertisement."

Should be removed.

**Comment by barton2526** [comment]
This is fixed in #65
