### ISSUE TITLE
Change hyperlink colour

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Site#66]
Several users have complained that hyperlinks aren't obvious; we should change the hyperlink colour to indicate their presence, nothing crazy though.

**Comment by dredlig** [comment]
Looks like links were intended to be red but are overridden by the specificity of `[data-background-color] a:not(.btn)` in `now-ui-kit.css`.  Not sure what the impact would be of removing that selector from that list around line 3386.

**Comment by grctest** [comment]
Done, the in-page hyperlinks are a readable purple/pink colour against the gun-grey background & the footer links are now white.

**Comment by RoboticMind** [comment]
Can you reopen this, the purple hyperlinks are very difficult to read.
