### ISSUE TITLE
Idea: Removing a large amount of info from the index page!

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Site#7]
I feel like we'd potentially be better off just deleting the following sections from the index page:
![image](https://user-images.githubusercontent.com/15861527/29672407-0de2adde-88e4-11e7-8306-4a294fca21fb.png)

Thoughts on the removal of the features section?

The 'possible BOINC software' section is speculative and doesn't provide meaningful information. Likewise, the snippet about types of BOINC projects could be included alongside a blurb about how anyone can run a BOINC project as well as cost estimates and links to guides?

**Comment by jimbo-slice** [comment]
Now that you mention it, it does seem like pointless clutter. There is some good information here, but it's mostly redundant and some aren't really useful. Here are my thoughts section by section:

1) POS/POB/DPOR/Voting - All of this is already explained higher up on the page.

2) Whitelist - We could remove this and mention/link the white-list within our opening section, perhaps somewhere within this paragraph:

_Gridcoin securely rewards volunteer distributed computing performed upon the BOINC platform in a decentralized manner on top of proof of stake. Projects range from attempting to cure diseases to searching for extraterrestrial life! You can distribute virtually any kind of distributed computing process through BOINC (utilizing GPU/CPU/Sensors/etc)._ 

3) Help Advance Science - The benefits of BOINC/GRC are already mentioned in our opening paragraphs.

4) Types of BOINC Projects: This data is already specified on our white-list page.

5) Potential BOINC tech - As you said, this is speculative and doesn't provide meaningful information.

**Comment by grctest** [comment]
In my current fork, I have entirely removed the feature and boinc sections from the index page.

Preview:
![image](https://user-images.githubusercontent.com/15861527/29689802-6f13ea54-891c-11e7-8adb-39c4261b0e1b.png)

**Comment by grctest** [comment]
Should we replace the world graphic with something else? Reference:
![image](https://user-images.githubusercontent.com/15861527/29689850-9595e3da-891c-11e7-879e-7e6735d65417.png)

I feel like the 'what is gridcoin' section is lacking without an image beside it, thoughts?

The section about Gridcoin needs to include some of the info which was removed (grc features & boinc info).

**Comment by jimbo-slice** [comment]
What about moving the centered logo to the left, and then moving the 'what is gridcoin' section up into the purple header, to the right of the logo?

**Comment by grctest** [comment]
> What about moving the centered logo to the left, and then moving the 'what is gridcoin' section up into the purple header, to the right of the logo?

I tried this out, it didn't look amazing to be honest.

---

Further relevant changes: https://github.com/gridcoin-community/Gridcoin-Site/issues/20
