### ISSUE TITLE
Update/Rework 3rd Party Apps page on site

### ISSUE THREAD

**Issue by barton2526** [gridcoin-community/Gridcoin-Site#77]

**Comment by grctest** [comment]
Perhaps worth just removing this page? We've not audited these projects, so perhaps directing users to them is irresponsible? They can find this info via BOINC web pages anyways?

**Comment by grctest** [comment]
@barton2526 Think we should remove this page? We don't audit these apps nor frequently check the links are still legit, it could be risky to maintain their presence on the site?

**Comment by barton2526** [comment]
I agree it should be removed

**Comment by grctest** [comment]
removed it in #140
