### ISSUE TITLE
Dynamically Update Version Number from GitHub Release Tag or Possibly MSI Version

### ISSUE THREAD

**Issue by barton2526** [gridcoin-community/Gridcoin-Site#79]
Needs investigation

**Comment by grctest** [comment]
We do have the new linux web environment, but it sounds overkill for something we can easily change manually

**Comment by RoboticMind** [comment]
Can this be done more easily now with the new setup?

**Comment by ShmoogleOsukami** [comment]
One option would be to have javascript pull the version number from GitHub via some method, It would mean we would not have to rebuild the site every time we release an update.
Alternatively we use a data file like we do with the blogs, I'm not sure if a rebuild is required for that, I'm not well versed with middleman. I believe there is a command that sort of live rebuilds the site or something.

**Comment by ShmoogleOsukami** [comment]
https://github.com/gridcoin-community/Gridcoin-Site/pull/161 Will fix this issue. :)

**Comment by barton2526** [comment]
#174 shows we need this more than ever

**Comment by barton2526** [comment]
#175 Closes this issue
