### ISSUE TITLE
Rewording of 'What is Gridcoin' Text

### ISSUE THREAD

**Issue by grc-H202** [gridcoin-community/Gridcoin-Site#85]
I think the 'What is Gridcoin' block of text needs rewording. This may be the very first thing someone reads about Gridcoin, and it should sound as professional as possible. Below is my proposed version. 

> "What is Gridcoin?" 
Gridcoin is an open source cryptocurrency (Ticker: GRC) which securely rewards volunteer computing performed on the [BOINC platform](http://boinc.berkeley.edu/).

>"What is BOINC?" 
[BOINC](http://boinc.berkeley.edu/) is an open source volunteer computing grid which combines the processing power of individual users for the purposes of scientific research. It's free to use and already home to 30+ projects spanning a range of scientific disciplines. Examples include protein structure prediction ([Rosetta@home](http://boinc.bakerlab.org/rosetta/)), mapping the Milky Way galaxy ([Milkyway@home](http://milkyway.cs.rpi.edu/milkyway/)), searching for record prime numbers [(Primegrid)](http://primegrid.com/), and tackling problems in public health and clean energy ([World Community Grid](https://www.worldcommunitygrid.org/discover.action)). 

> "How can I participate?"
> Individuals: Join BOINC and start earning Gridcoin for your contributions! See the 'Guides' section for details.
> Researchers and institutions: Tap into the spare processing power of tens of thousands of volunteers, and create your own BOINC project for free! In turn, the Gridcoin network can reward your project's userbase to encourage participation and improve user retention.

**Comment by jring-o** [comment]
Remove contractions = )

**Comment by barton2526** [comment]
Done @jring-o
