### ISSUE TITLE
Explain that newbie blocks are capped at 500 GRC

### ISSUE THREAD

**Issue by barton2526** [gridcoin-community/Gridcoin-Site#90]
Two users in the GRC Discord noted that they were surprised to see their POR rewards capped at 500.  After further examination both users had not yet staked their newbie block and were under the impression that POR rewards accumulated for 180 days (which is true, but is not true for the first POR stake, the newbie block).  This should be clarified on the site, probably in the solo guide.

**Comment by grctest** [comment]
AFAIK The 'newbie block' shouldn't exist - the stake weight boost was removed so other aspects of it like the limit mentioned should also be removed too, no?

**Comment by barton2526** [comment]
This is no longer true.   Closing
