### ISSUE TITLE
Official GRC MacOS DMG link needed on home page

### ISSUE THREAD

**Issue by acey1** [gridcoin-community/Gridcoin-Site#95]
Now that production has auto tools, we need an official GRC MacOS DMG release and link on the home page for MacOS. Currently the link given on the home page points to the Git Jiro method which works fine, but can lag behind a new release. This is neither a suitable or secure way to professionally distribute an official GRC release.

**Comment by grctest** [comment]
Do we have a link for an official MacOS DMG?

**Comment by acey1** [comment]
The Jiro team is presently handling it. 

https://github.com/Git-Jiro/homebrew-jiro/releases/

However the GRC MacOS DMG still has issues reported separately.  Basically our auto tools version is missing some icons inside the app and it does make a proper app bundle that can  be installed on a virgin Mac that does not have Homebrew and all dependancies installed on it separately.

**Comment by grctest** [comment]
This has been implemented 👍

**Comment by acey1** [comment]
I agree that it has been implemented for some now, but is still linked to the Jiro builds at:

https://github.com/Git-Jiro/homebrew-jiro/releases/

If you click on Windows downloads for example, one receives the official wallet download directly from the Gridcoin website and not send off to another place to download it. I seek seamless official MacOS integration into the Gridcoin download page. Whereas when a new version is released, Travis builds all OS versions and links them directly to the download page for security and reliability.

If you wish for Jiro to continue to host the MacOS builds, we are happy to do so. But I think it is unwise for Gridcoin to rely on a third party for this type of thing.
