### ISSUE TITLE
Update URL for Universe@home on Whitelist page

### ISSUE THREAD

**Issue by troyengel** [gridcoin-community/Gridcoin-Site#96]
Hi team, the Whitelist link for the Universe has a `www` up front, but they don't have a SSL for that host, right now it's:

* https://www.gridcoin.us/Guides/whitelist.htm -> https://www.universeathome.pl/universe/

That needs to be updated to just https://universeathome.pl/universe/ where they run a proper cert.

**Comment by Pythonix** [comment]
Looks like they corrected it. I think this can be closed.

**Comment by troyengel** [comment]
Right on, thanks. Closing this up.
