### ISSUE TITLE
Rearrange Community and Resources Pull Down Menu

### ISSUE THREAD

**Issue by jring-o** [gridcoin-community/Gridcoin-Site#99]
I'm thinking two sections for the Community pull down.

Essentials:
-Announcements (is it really a blog?)
-Contact Us
-Github
-Twitter
-Reddit
-Steemit
-Facebook
-CryptoCurrency Talk (instead of just saying "forum")

Chat:
-Discord
-Slack
-Rocket Chat
-Telegram

Then move the remaining items to the Resources pull down.

credit rino for the initial comment about the... unique... order of our pull downs.

**Comment by grctest** [comment]
https://github.com/gridcoin-community/Gridcoin-Site/pull/105

Look good? @jring-o
